/*export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};*/


const user={
  "login": "AsarAman",
  "id": 103176641,
  "node_id": "U_kgDOBiZZwQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/103176641?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AsarAman",
  "html_url": "https://github.com/AsarAman",
  "followers_url": "https://api.github.com/users/AsarAman/followers",
  "following_url": "https://api.github.com/users/AsarAman/following{/other_user}",
  "gists_url": "https://api.github.com/users/AsarAman/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AsarAman/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AsarAman/subscriptions",
  "organizations_url": "https://api.github.com/users/AsarAman/orgs",
  "repos_url": "https://api.github.com/users/AsarAman/repos",
  "events_url": "https://api.github.com/users/AsarAman/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AsarAman/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Syed Asar Aman",
  "company": null,
  "blog": "",
  "location": "Pakistan",
  "email": null,
  "hireable": null,
  "bio": "Hey guys! I am Syed ASAR Aman a Front-End Developer and I have experience working with Javascript, React, Tailwind CSS and Bootstrap, etc...",
  "twitter_username": "aman_asar",
  "public_repos": 30,
  "public_gists": 0,
  "followers": 8,
  "following": 7,
  "created_at": "2022-04-07T08:06:51Z",
  "updated_at": "2022-08-25T18:15:08Z"
}

export default user
